<?php 
/**
 * @category    Morphes
 * @package     Morphes_Filters
 * @copyright   Copyright (c) http://www.morphes.ru
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/** 
 * @author Morphes Team
 */
/* @var $this Morphes_Filters_Block_Filter_Attribute */
/* @var $filters Morphes_Filters_Helper_Data */ $filters = Mage::helper(strtolower('Morphes_Filters'));
/* @var $showmore MorphesPro_FilterShowMore_Helper_Data */ $showmore = Mage::helper(strtolower('MorphesPro_FilterShowMore'));
$MAX_ROW_COUNT = $showmore->getMaxRowCount(); // 20
$MAX_COLUMN_COUNT = $showmore->getMaxColumnCount(); // 4
$items = $this->getItems();
list($rowCount, $columnCount) = $showmore->getPopupDimensions($items, $MAX_ROW_COUNT, $MAX_COLUMN_COUNT);
?>
<div class="m-filter-popup">
<ol class="m-rows" data-max-rows="<?php echo $MAX_ROW_COUNT ?>">
    <?php for($rowIndex = 0; $rowIndex < $rowCount; $rowIndex++) : ?>
    <li>
        <ol class="m-columns">
            <?php for ($columnIndex = 0; $columnIndex < $columnCount; $columnIndex++) : if ($columnIndex * $rowCount + $rowIndex < count($items)) : ?>
            <?php $_item = $items[$columnIndex * $rowCount + $rowIndex]; ?>
            <li <?php if ($_item->getMShowSelected()): ?>class="m-selected-ln-item"<?php endif; ?>>
                <?php if ($_item->getMSelected()): ?>
                <span class="m-selected-filter-item"><?php echo $this->escapeHtml($_item->getLabel()) ?></span>
                <?php else : ?>
                <?php if ($_item->getCount() > 0): ?>
                    <a href="#" onClick="return jQuery.mShowMorePopupApply('<?php echo $_item->getSeoValue() ?>');"
                       title="<?php echo $this->escapeHtml($_item->getLabel()) ?>"><?php echo $this->escapeHtml($_item->getLabel()) ?></a>
                    <?php else: echo $this->escapeHtml($_item->getLabel()) ?>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if (Mage::getStoreConfigFlag('morphes_filters/display/count')) : ?>
                    (<?php echo $_item->getCount() ?>)
                <?php endif; ?>
            </li>
            <?php endif; endfor; ?>
        </ol>
    </li>
    <?php endfor; ?>
</ol>
</div>
