<?php if (!Mage::getSingleton('customer/session')->isLoggedIn()){?>
<div id="onepagecheckout_forgotbox" style="display: none;" class='op_login_area'>
<div id='morphes-form-forgot'>
<div class="close-window-login" onclick="hideJ2tOverlay()">&nbsp;</div>
	<!--<div class='close_la' onclick='close_login();'></div>--><br/><br/>
<h1><?php echo $this->__('Забыли пароль?') ?></h1>
<?php
$forgot_url	= $this->getUrl('*/*/forgotpassword', array('_secure'=>(!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS']==='on')));
$http_mode	= (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS']==='on');
if($http_mode)
	$forgot_url	= str_replace('http:', 'https:', $forgot_url);  
?>
     <!--<form action="<?php echo $forgot_url ?>" method="post" id="forgot-password-form">-->
        <div class="boxcontent form_fields">
            <p><?php echo $this->__('Please enter your email below and we will send you a new password.') ?></p>
			<div class='full'>
				<label>
					<?php echo $this->__('Email') ?>
				</label>
				<sup>*</sup>
				<div class="data_area">
					<input type="text" name="email" alt="email" id="email_address" class="input-text required-entry validate-email" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" />
				</div>
            </div>
        </div>
        <div class="buttons-set">
            <p class="back-link"><a href="javascript:void(0)" class="onepagecheckout_loginlink" onclick='getlogin();'><small>&laquo; </small><?php echo $this->__('Back to Login') ?></a></p>
            <button type="submit" title="<?php echo $this->__('Submit') ?>" id="btn-forgot" class="css3buttongreen green-button" onclick='getforgot()'><span><span><?php echo $this->__('Submit') ?></span></span></button>
            <span class="please-wait" id="forgot-please-wait" style="display:none;">
                <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt=""/>
            </span>
        </div>
  <!--  </form> -->
    <script type="text/javascript">
    //<![CDATA[
        var forgotForm = new VarienForm('forgot-password-form', true);
    //]]>
    </script>
</div>
</div>
<?php }?>
