<?php
/**
 * 	Created by ORBA|we-commerce your business -> orba.pl
 */
?>
<script type="text/javascript">
    //<![CDATA[
    if (typeof lastPrice == 'undefined') {
        lastPrice = false;
    }
    if (typeof quoteBaseGrandTotal == 'undefined') {
        quoteBaseGrandTotal = false;
    }
    //]]>
</script>
<?php
//collect data for sheepla
//get info on email of the customer
$city = $this->getAddress()->getCity();
if (empty($city)) {
    $customer = Mage::getSingleton('customer/session')->getCustomer();
    $city = $customer->getCity();
}
//double check
if (empty($city)) {
    $city = '';
}


$temp = array();
$groups = array();
$shConf = array();
$showSheepla = false;
?>

<?php if (!($_shippingRateGroups = $this->getShippingRates())): ?>
    <p><?php echo $this->__('Sorry, no quotes are available for this order at this time.') ?></p>
<?php else: ?>
    <dl class="sp-methods">
        <?php $shippingCodePrice = array(); ?>
        <?php
        $_sole = count($_shippingRateGroups) == 1;
        foreach ($_shippingRateGroups as $code => $_rates):
            ?>
            <dt>
            <?php if ($code == 'sheepla'): ?>
                <!-- group and sort sheepla rates -->
                <?php
                $temp = array();
                $groups = array();
                $shConf = array();
                $showSheepla = false;

                foreach ($_rates as $_rate) {
                    $conf = Mage::getStoreConfig('sheepla/' . $_rate->getMethod());
                    $shConf[$_rate->getCode()] = $conf;

                    if ($conf['hidden'] == 0 && $conf['enabled'] == 1) {
                        $temp['sort_' . $conf['sort_order']] = $_rate;
                        $showSheepla = true;
                    }
                }
                ksort($temp);
                $_rates = $temp;
                ?>

                <?php $sConf = Mage::getStoreConfig('sheepla'); ?>
                <?php if ($showSheepla && $sConf['advanced']['show_label_at_checkout']): ?>
                    <p>
                        <?php
                        if (isset($sConf['advanced']['custom_label']) && !empty($sConf['advanced']['custom_label'])) {
                            echo $sConf['advanced']['custom_label'];
                        } else {
                            echo $this->__('Robust delivery by Sheepla!');
                        }
                        ?>
                    </p>
                <?php endif; ?>

            <?php else: ?>
                <?php echo $this->getCarrierName($code) ?>
            <?php endif; ?>
            </dt>
            <dd>
                <ul>
                    <?php
                    $_sole = $_sole && count($_rates) == 1;
                    foreach ($_rates as $_rate):
                        ?>
                        <?php $shippingCodePrice[] = "'" . $_rate->getCode() . "':" . (float) $_rate->getPrice(); ?>
                        <li>
                            <?php if ($_rate->getErrorMessage()): ?>
                                <ul class="messages"><li class="error-msg"><ul><li><?php echo $_rate->getErrorMessage() ?></li></ul></li></ul>
                            <?php else: ?>
                                <?php if ($_sole) : ?>
                                    <span class="no-display"><input name="shipping_method" type="radio" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>" checked="checked" /></span>
                                    <?php if (key_exists($_rate->getCode(), $shConf) && !empty($shConf[$_rate->getCode()]['template_id'])): ?> 

                                        <script type="text/javascript">
                                            //<![CDATA[		
                                            sheepla_onclick('<?php echo $shConf[$_rate->getCode()]['template_id']; ?>', '.sheepla-sdk-area', '<?php echo $city; ?>', '<?php echo $_rate->getCode(); ?>', this);
                                            //]]>
                                        </script><?php endif; ?>
                                <?php else: ?>
                                    <input name="shipping_method" 
                                           type="radio" 
                                           value="<?php echo $_rate->getCode() ?>" 
                                           id="s_method_<?php echo $_rate->getCode() ?>"
                                           <?php if ($_rate->getCode() === $this->getAddressShippingMethod()) echo ' checked="checked"' ?> 
                                           class="radio" 
                                           <?php if (key_exists($_rate->getCode(), $shConf) && !empty($shConf[$_rate->getCode()]['template_id'])): ?> 
                                               onclick="sheepla_onclick('<?php echo $shConf[$_rate->getCode()]['template_id']; ?>', '.sheepla-sdk-area', '<?php echo $city; ?>', '<?php echo $_rate->getCode(); ?>', this);"
                                           <?php else: ?>
                                               onclick="sheepla_onclick(false, '.sheepla-sdk-area', '<?php echo $_rate->getCode(); ?>', '<?php echo $city; ?>', this);"
                                           <?php endif; ?>
                                           />

                                    <?php if ($_rate->getCode() === $this->getAddressShippingMethod()): ?>
                                        <script type="text/javascript">
                                            //<![CDATA[
                        <?php if (key_exists($_rate->getCode(), $shConf) && !empty($shConf[$_rate->getCode()]['template_id'])): ?>
                                                sheepla_onclick('<?php echo $shConf[$_rate->getCode()]['template_id']; ?>', '.sheepla-sdk-area', '<?php echo $city; ?>', '<?php echo $_rate->getCode(); ?>', this);
                        <?php endif; ?>
                                            lastPrice = <?php echo (float) $_rate->getPrice(); ?>;
                                            //]]>
                                        </script>
                                    <?php endif; ?>

                                <?php endif; ?>
                                <label for="s_method_<?php echo $_rate->getCode() ?>">
                                    <?php if (isset($shConf[$_rate->getCode()]) && isset($shConf[$_rate->getCode()]['logo_url']) && $shConf[$_rate->getCode()]['logo_url']): ?>
                                        <span class="sheepla-carrier-logo-container">
                                            <img class="sheepla-carrier-logo" src="<?php echo $shConf[$_rate->getCode()]['logo_url']; ?>" alt="<?php echo $_rate->getMethodTitle(); ?>" />
                                        </span>
                                    <?php endif; ?>
                                    <?php echo $_rate->getMethodTitle() ?>
                                    <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                                    <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>
                                    <?php echo $_excl; ?>
                                    <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                                        (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                                    <?php endif; ?>
                                </label>
                            <?php endif ?>


                        </li>
                    <?php endforeach; ?>
                </ul>
            </dd>
        <?php endforeach; ?>
    </dl>
    <script type="text/javascript">
        //<![CDATA[
    <?php if (!empty($shippingCodePrice)): ?>
            var shippingCodePrice = {<?php echo implode(',', $shippingCodePrice); ?>};
    <?php endif; ?>

        $$('input[type="radio"][name="shipping_method"]').each(function(el) {
            Event.observe(el, 'click', function() {
                if (el.checked == true) {
                    var getShippingCode = el.getValue();
    <?php if (!empty($shippingCodePrice)): ?>
                        var newPrice = shippingCodePrice[getShippingCode];
                        if (!lastPrice) {
                            lastPrice = newPrice;
                            quoteBaseGrandTotal += newPrice;
                        }
                        if (newPrice != lastPrice) {
                            quoteBaseGrandTotal += (newPrice - lastPrice);
                            lastPrice = newPrice;
                        }
    <?php endif; ?>
                    checkQuoteBaseGrandTotal = quoteBaseGrandTotal;
                    return false;
                }
            });
        });
        //]]>
    </script>
<?php endif; ?>

<div class="sheepla-sdk-area">&nbsp;</div>