<?php
/**
 * @category    Morphes
 * @package     Morphes_Admin
 * @copyright   Copyright (c) http://www.morphes.ru
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * This template displays first child wrapped in additional div. 
 */
/* @var $this Morphes_Admin_Block_Dynamic */
?>
<?php if (($_html = $this->getChildHtml()) || $this->getForceRender()) : ?>
<div class="m-dynamic" <?php if ($_id = $this->getDynamicId()) : ?>id="<?php echo $_id ?>"<?php endif; ?>>
<?php echo $_html ?>
</div>
<?php endif; ?>