<?php 
/**
 * @category    Morphes
 * @package     MorphesPro_FilterSlider
 * @copyright   Copyright (c) http://www.morphes.ru
 * @license     http://www.morphes.ru/license  Proprietary License
 */
/** 
 * Template for showing options for filter as a slider 
 * @author Morphes Team
 * Injected instead of standard catalog/layer/filter.phtml in Morphes_Filters_Block_Filter_Attribute init() method.
 * This template is overridden by copying (template body was pasted from catalog/layer/filter.phtml 
 * and modified as needed). All changes are marked with comments.
 */
/* @var $this Morphes_Filters_Block_Filter_Price */
?>
<?php /* @var $_helper Morphes_Filters_Helper_Data */ $_helper = Mage::helper(strtolower('Morphes_Filters')); ?>
<?php /* @var $_superHelper MorphesPro_FilterSuperSlider_Helper_Data */ $_superHelper = Mage::helper(strtolower('MorphesPro_FilterSuperSlider')); ?>
<?php /* @var $_slider MorphesPro_FilterSlider_Helper_Data */ $_slider = Mage::helper(strtolower('MorphesPro_FilterSlider'));?>
<?php /* @var $_filter Morphes_Filters_Model_Filter_Price */ $_filter = $this->getFilter(); ?>
<?php $_id = $_helper->getFilterName($this, $_filter); ?>

	<div class="m-slider-values">
        <?php if ($_filter->getFilterOptions()->getSliderManualEntry()) : ?>
        <span id="<?php echo $_id ?>-applied" class="m-slider-selected-value">
            <?php echo $_superHelper->beforeInput($_filter->getFilterOptions()) ?>
            <input type="text" class="m-slider m-from" size="2" value="<?php echo $_filter->getCurrentRangeLowerBound() ?>" /><?php echo $_superHelper->afterInput($_filter->getFilterOptions()) ?>
            <?php echo $_superHelper->__('&nbsp;-&nbsp;&nbsp;') ?>
            <?php echo $_superHelper->beforeInput($_filter->getFilterOptions()) ?>
            <input type="text" class="m-slider m-to" size="2" value="<?php echo $_filter->getCurrentRangeHigherBound() ?>" /><?php echo $_superHelper->afterInput($_filter->getFilterOptions()) ?>
        </span>
        <?php else: ?>
		<span id="<?php echo $_id ?>-applied" class="m-slider-selected-value"><?php echo $_helper->__('%s - %s', $_superHelper->formatNumber($_filter->getCurrentRangeLowerBound(), $_filter->getFilterOptions()), $_superHelper->formatNumber($_filter->getCurrentRangeHigherBound(), $_filter->getFilterOptions()))?></span>
		<?php endif; ?>
	</div>
<div id="<?php echo $_id ?>-track" class="m-filter-slider">
	<div id="<?php echo $_id ?>-span" class="m-slider-span"></div>
	<div id="<?php echo $_id ?>-from" class="m-slider-from"></div>
	<div id="<?php echo $_id ?>-to" class="m-slider-to"></div>
</div>
<script type="text/javascript">
//<![CDATA[
MorphesPro.filterSuperSlider('<?php echo $_id ?>', {
	rangeFrom: <?php echo $_filter->getLowestPossibleValue() ?>,
	rangeTo: <?php echo $_filter->getHighestPossibleValue() ?>,
	appliedFrom: <?php echo $_filter->getCurrentRangeLowerBound() ?>,
	appliedTo: <?php echo $_filter->getCurrentRangeHigherBound() ?>,
	numberFormat: "<?php echo addslashes($_filter->getFilterOptions()->getSliderNumberFormat()) ?>",
	appliedFormat: '<?php echo $_helper->__('__0__ - __1__') ?>',
	url: '<?php echo $_slider->getUrl($_filter->getRequestVar()) ?>',
	clearUrl: '<?php echo $_slider->getClearUrl($_filter->getRequestVar()) ?>',
	manualEntry: <?php echo $_filter->getFilterOptions()->getSliderManualEntry() ? 1 : 0 ?>,
	formatThreshold: <?php echo $_filter->getFilterOptions()->getSliderThreshold() ? $_filter->getFilterOptions()->getSliderThreshold() : 0 ?>,
    numberFormat2: "<?php echo addslashes($_filter->getFilterOptions()->getSliderNumberFormat2()) ?>",
    //
    <?php //if($_filter->getName()=="Цена") { ?>
		existingValues: <?php echo $_filter->getFilterOptions()->getSliderUseExistingValues() ? json_encode($_filter->getExistingValues()) : '{}' ?>,
    <?php //} else { ?>
    	//existingValues: [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000],
    <?php //} ?>

    decimalDigits: <?php echo $_filter->getFilterOptions()->getSliderDecimalDigits() ?>,
    decimalDigits2: <?php echo $_filter->getFilterOptions()->getSliderDecimalDigits2() ?>,
    thousandSeparator: '<?php echo $_filter->getFilterOptions()->getThousandSeparator() ?>',
    decimalSymbol: '<?php echo $_superHelper->getDecimalSymbol() ?>',
    groupSymbol: '<?php echo $_superHelper->getGroupSymbol() ?>'
});
//]]>
</script>
