</div></div></div></div>
<div class="main-content-bottom"><div><div>&nbsp;</div></div></div>



<br/>
<div class="main-content-top"><div><div>&nbsp;</div></div></div>
<div class="main-border-left">
    <div class="main-border-right">
        <div class="main-content">
            <div>
                <h1 style="color: #386393">Продажа надувных и каркасных бассейнов для дачи</h1>
                <h2 style="color: #565656;font-weight: normal;font-size: 17px;">Надувные бассейны</h2>
                <p style="font-size: 11px;color:#565656">У вас небольшой дачный участок где мало места для сооружения стационарного бассейна? Тогда Вы можете купить <b>надувной бассейн Easy Set</b> - самый простой и быстро возводимый бассейн Intex для дачи. Установка этого бассейна займет считанные минуты, достаточно лишь надуть 
                    верхнее кольцо.</p>
                <span class="nad-popup" style="cursor:pointer;"><img class='arrow' src="/media/tr2.jpg" style="float:left; margin-top:4px; margin-right: 3px;"/> <font style="text-decoration:underline;color:#386393;font-weight:bold" >Размеры надувных бассейнов</font></span>
                <div class="nad-div" style="height: 231px;display:none">
                     <div class="col-1" style="width:190px; float:left">
                           <div style="margin-left: 59px;margin-top: 9px;">
                                <h6 style="margin-left: -59px;margin-bottom:7px;margin-top: 24px;text-align:center;color:#28517B !important">Надувные бассейны<br/> Easy Set</h6>
                                <a href="/naduvnie-basseiny/kruglie-basseini-easy-set/basseiny-easy-set.html?diametr_test=244%2C244&high_test=76%2C76&m-layered=1&m-layered=1" style="color:#386393;font-size:11px;"><img src="/media/arrows.png" style="float:left;margin-top: 5px;margin-right: 4px;"/> 244x76 см</a><br/>
                                <a href="/naduvnie-basseiny/kruglie-basseini-easy-set/basseiny-easy-set.html?diametr_test=305%2C305&high_test=76%2C76&m-layered=1&m-layered=1" style="color:#386393;font-size:11px;"><img src="/media/arrows.png" style="float:left;margin-top: 5px;margin-right: 4px;"/> 306x76 см</a><br/>
                                <a href="/naduvnie-basseiny/kruglie-basseini-easy-set/basseiny-easy-set.html?diametr_test=366%2C366&high_test=76%2C76&m-layered=1&m-layered=1" style="color:#386393;font-size:11px;"><img src="/media/arrows.png" style="float:left;margin-top: 5px;margin-right: 4px;"/> 366x76 см</a><br/>
                                <a href="/naduvnie-basseiny/kruglie-basseini-easy-set/basseiny-easy-set.html?diametr_test=366%2C366&high_test=91%2C91&m-layered=1&m-layered=1" style="color:#386393;font-size:11px;"><img src="/media/arrows.png" style="float:left;margin-top: 5px;margin-right: 4px;"/> 366x91 см</a><br/>
                           </div>
                           <img src="/media/1.jpg" style="margin-left: 21px;margin-top: 8px;"/>

                     </div>
                     <div class="col-2" style="width:188px; float:left">
                           <div style="margin-left: 59px;margin-top: 9px;">
                                <h6 style="margin-left: -45px;margin-bottom:7px;margin-top: 24px;text-align:center;color:#28517B !important">Надувные бассейны<br/> Easy Set</h6>
                                <a href="/naduvnie-basseiny/kruglie-basseini-easy-set/basseiny-easy-set.html?diametr_test=457%2C457&high_test=91%2C91&m-layered=1&m-layered=1" style="color:#386393;font-size:11px;"><img src="/media/arrows.png" style="float:left;margin-top: 5px;margin-right: 4px;"/> 457x91 см</a><br/>
                                <a href="/naduvnie-basseiny/kruglie-basseini-easy-set/basseiny-easy-set.html?diametr_test=457%2C457&high_test=107%2C107&m-layered=1&m-layered=1" style="color:#386393;font-size:11px;"><img src="/media/arrows.png" style="float:left;margin-top: 5px;margin-right: 4px;"/> 457x107 см</a><br/>
                                <a href="/naduvnie-basseiny/kruglie-basseini-easy-set/basseiny-easy-set.html?diametr_test=457%2C457&high_test=122%2C122&m-layered=1&m-layered=1" style="color:#386393;font-size:11px;"><img src="/media/arrows.png" style="float:left;margin-top: 5px;margin-right: 4px;"/> 457x122 см</a><br/>
                                <a href="/naduvnie-basseiny/kruglie-basseini-easy-set/basseiny-easy-set.html?diametr_test=549%2C549&high_test=122%2C122&m-layered=1&m-layered=1" style="color:#386393;font-size:11px;"><img src="/media/arrows.png" style="float:left;margin-top: 5px;margin-right: 4px;"/> 549x122 см</a><br/>
                           </div>
                           <img src="/media/2.jpg" style="margin-left: 21px;margin-top: 8px;"/>

                     </div>
                     <div class="col-3" style="width:188px; float:left">
                           <div style="margin-left: 59px;margin-top: 9px;">
                                <h6 style="margin-left: -29px;margin-top: 24px;margin-bottom:7px;text-align:center;color:   #28517B !important">Овальные бассейны<br/> Oval Frame</h6>
                                <a href="http://dachniki-club.ru/naduvnie-basseiny/ovalnie-basseini-oval-frame/basseiny-oval-frame.html?high_test=107%2C107&length_test=549%2C549&m-layered=1&width_test=305%2C305&m-layered=1" style="color:#386393;font-size:11px;"><img src="/media/arrows.png" style="float:left;margin-top: 5px;margin-right: 4px;"/> 549x305x107 см</a><br/>
                                <a href="/naduvnie-basseiny/ovalnie-basseini-oval-frame/basseiny-oval-frame.html?high_test=122%2C122&length_test=610%2C610&m-layered=1&width_test=366%2C366&m-layered=1" style="color:#386393;font-size:11px;"><img src="/media/arrows.png" style="float:left;margin-top: 5px;margin-right: 4px;"/> 610x366x122 см</a><br/>
                           </div>
                           <img src="/media/3.jpg" style="margin-left: 21px;margin-top: 57px;"/>

                     </div>



                </div>
                <br/><br/>
<h2 style="color: #565656;font-weight: normal;font-size: 17px;">Каркасные бассейны</h2>
<p style="font-size: 11px;color:#565656">Если ваш дачный участок от 6 соток и более, Вы можете остановить свой выбор на каркасном бассейне. Каркасные бассейны дороже надувных, но они более надежны и долговечны, срок службы каркасных бассейнов до 10 лет. За счет своего металлического каркаса выдерживают большие нагрузки. Уровень наполненияэтих бассейнов порядка 90%.</p>
<span class="kar-popup" style="cursor:pointer;"><img class="arrow" src="/media/tr2.jpg" style="float:left; margin-top:4px; margin-right: 3px;"/> <font style="text-decoration:underline;color:#386393;font-weight:bold" >Размеры каркасных бассейнов</font></span>
                <div class="kar-div" style="height: 231px;display:none">
                     <div class="col-3" style="width:188px; float:left; height: 278px;">
                           <div style="margin-left: 59px;margin-top: 9px;">
                                <h6 style="margin-left: -45px;margin-top: 24px;text-align:center;margin-bottom:7px;color:   #28517B !important">Каркасные бассейны<br/> Metal Frame</h6>
                                <a href="/karkasnie-basseini/kruglie-basseiny/basseiny-metall-frame-pools.html?diametr_test=306%2C306&high_test=76%2C76&m-layered=1&m-layered=1" style="color:#386393;font-size:11px;"><img src="/media/arrows.png" style="float:left;margin-top: 5px;margin-right: 4px;"/> 306x76 см</a><br/>
                                <a href="/karkasnie-basseini/kruglie-basseiny/basseiny-metall-frame-pools.html?diametr_test=306%2C306&high_test=76%2C99&m-layered=1&m-layered=1" style="color:#386393;font-size:11px;"><img src="/media/arrows.png" style="float:left;margin-top: 5px;margin-right: 4px;"/> 366x76-99 см</a><br/>
                           </div>
                           <img src="/media/4.jpg" style="margin-left: 21px;margin-top: 91px;"/>

                     </div>                  
                     <div class="col-1" style="width:190px; float:left; height: 278px;">
                           <div style="margin-left: 59px;margin-top: 9px;">
                                <h6 style="margin-left: -45px;text-align:center;margin-top: 24px;margin-bottom:7px;color:   #28517B !important">Каркасные бассейны<br/> Metal Frame</h6>
                                <a href="/karkasnie-basseini/kruglie-basseiny/basseiny-metall-frame-pools.html?diametr_test=457%2C457&high_test=91%2C91&m-layered=1&m-layered=1" style="color:#386393;font-size:11px;"><img src="/media/arrows.png" style="float:left;margin-top: 5px;margin-right: 4px;"/> 457x91 см</a><br/>
                                <a href="/karkasnie-basseini/kruglie-basseiny/basseiny-metall-frame-pools.html?diametr_test=457%2C457&high_test=107%2C107&m-layered=1&m-layered=1" style="color:#386393;font-size:11px;"><img src="/media/arrows.png" style="float:left;margin-top: 5px;margin-right: 4px;"/> 457x107 см</a><br/>
                                <a href="/karkasnie-basseini/kruglie-basseiny/basseiny-metall-frame-pools.html?diametr_test=457%2C457&high_test=122%2C122&m-layered=1&m-layered=1" style="color:#386393;font-size:11px;"><img src="/media/arrows.png" style="float:left;margin-top: 5px;margin-right: 4px;"/> 457x122 см</a><br/>
                                <a href="/karkasnie-basseini/kruglie-basseiny/basseiny-metall-frame-pools.html?diametr_test=549%2C549&high_test=107%2C107&m-layered=1&m-layered=1" style="color:#386393;font-size:11px;"><img src="/media/arrows.png" style="float:left;margin-top: 5px;margin-right: 4px;"/> 549x107 см</a><br/>
                                <a href="/karkasnie-basseini/kruglie-basseiny/basseiny-metall-frame-pools.html?diametr_test=549%2C549&high_test=122%2C122&m-layered=1&m-layered=1" style="color:#386393;font-size:11px;"><img src="/media/arrows.png" style="float:left;margin-top: 5px;margin-right: 4px;"/> 549x122 см</a><br/> 
                                <a href="/karkasnie-basseini/kruglie-basseiny/basseiny-metall-frame-pools.html?diametr_test=732%2C732&high_test=132%2C132&m-layered=1&m-layered=1" style="color:#386393;font-size:11px;"><img src="/media/arrows.png" style="float:left;margin-top: 5px;margin-right: 4px;"/> 732x132 см</a><br/>                                                                
                           </div>
                           <img src="/media/5.jpg" style="margin-left: -16px;margin-top: 14px;"/>

                     </div>
                     <div class="col-2" style="width:188px; float:left; height: 278px;">
                           <div style="margin-left: 59px;margin-top: 9px;">
                                <h6 style="margin-left: -45px;text-align:center;margin-top: 24px;margin-bottom:7px;color:   #28517B !important">Каркасные бассейны<br/> Ultra Frame</h6>
                                <a href="/karkasnie-basseini/kruglie-basseiny/basseini-ultra-frame-pools.html?diametr_test=488%2C488&m-layered=1" style="color:#386393;font-size:11px;"><img src="/media/arrows.png" style="float:left;margin-top: 5px;margin-right: 4px;"/> 488x122 см</a><br/>
                                <a href="/karkasnie-basseini/kruglie-basseiny/basseini-ultra-frame-pools.html?diametr_test=549%2C549&high_test=132%2C132&m-layered=1&m-layered=1" style="color:#386393;font-size:11px;"><img src="/media/arrows.png" style="float:left;margin-top: 5px;margin-right: 4px;"/> 549x132 см</a><br/>
                           </div>
                           <img src="/media/6.jpg" style="margin-left: 21px;margin-top: 87px;"/>

                     </div>
                     <div class="col-3" style="width:285px; float:left; height: 266px;">
                           <div style="margin-left: 118px;margin-top: 9px;">
                                <h6 style="margin-left: -63px;margin-top: 24px;text-align:center;margin-bottom:7px;center;color:#28517B !important">Каркасные бассейны<br/> Ultra Frame</h6>
                                <a href="/karkasnie-basseini/priamougolnie-basseini/basseini-restangular-pools.html?high_test=132%2C132&length_test=549%2C549&m-layered=1&width_test=274%2C274&m-layered=1" style="color:#386393;font-size:11px;"><img src="/media/arrows.png" style="float:left;margin-top: 5px;margin-right: 4px;"/> 549x274x132 см</a><br/>
                                <a href="/karkasnie-basseini/priamougolnie-basseini/basseini-restangular-pools.html?high_test=132%2C132&length_test=732%2C732&m-layered=1&width_test=274%2C274&m-layered=1" style="color:#386393;font-size:11px;"><img src="/media/arrows.png" style="float:left;margin-top: 5px;margin-right: 4px;"/> 732x274x132 см</a><br/>
                                <a href="/karkasnie-basseini/priamougolnie-basseini/basseini-restangular-pools.html?high_test=132%2C132&length_test=975%2C975&m-layered=1&width_test=488%2C488&m-layered=1" style="color:#386393;font-size:11px;"><img src="/media/arrows.png" style="float:left;margin-top: 5px;margin-right: 4px;"/> 975x488x132 см</a><br/> 
                           </div>
                           <img src="/media/7.jpg" style="margin-left: 21px;margin-top: 8px;"/>

                     </div>
                     <div class="col-3" style="width:287px; float:left; height: 266px">
                           <div style="margin-left: 139px;margin-top: 9px;">
                                <h6 style="margin-left: -66px;text-align:center;margin-bottom:7px;margin-top: 24px;color:   #28517B !important">Каркасные бассейны<br/> Sequola Spirit</h6>
                                <a href="/karkasnie-basseini/kruglie-basseiny/basseiny-sequoia-spirit-pools.html?diametr_test=508%2C508&high_test=124%2C124&m-layered=1&m-layered=1" style="color:#386393;font-size:11px;"><img src="/media/arrows.png" style="float:left;margin-top: 5px;margin-right: 4px;"/> 508x124 см</a><br/>                              
                           </div>
                           <img src="/media/8.jpg" style="margin-left: 59px;margin-top: 48px;"/>

                     </div>                                         
                   </div><br/><br/>
                     <p style="font-size: 11px;color:#565656">Каталог бассейнов Интекс (Intex) представлен линией <b>надувных бассейнов Easy Set</b> : бассейны мини диаметром от 2.44 м. и большие до 5.49 м;
                        <br/><b>Карасные бассейны Metal Frame</b> представлены диаметром от 3.05 м. до 7.32 м; 
                        <br/><b>Карасные бассейны Ultra Frame</b> выпускаются диаметром от 4.88 м. до 5.49 м., <b>прямоугольные Ultra Frame</b> длиной от 5.49 м. до 9.75 м.;<br/>
                        Основные преимущества недорогих готовых надувных и каркасных  бассейнов Intex (Интекс) - цена, надежность и простота монтажа. <br/> Создать искусственный водоем из надувного бассейна можно за 20-30 минут, каркасные бассейны intex собираются немного дольше, но для установки их на дачном участке потребуется не более 45-60 минут. <br/>
                        Бассейны для дачи компании Intex (Интекс) занимают лидирующее положение в сегменте сборно-разборных бассейнов, они наиболее оптимальны по соотношению цены, качества и потребительских свойств. 
                        <br/>Сборный бассейн Intex (Интекс) - это недорогой бассейн для дачи, который не испортит ландшафт вашего участка и не повредит газон. Установить его можно на любую ровную поверхность, а при желании всегда можно быстро убрать, слив воду в ближайший пруд или водоотводную канаву. 
                        <br/><b>Купить бассейн для дачи</b> недорого Вы можете, сделав заказ непосредственно на сайте интернет-магазина (круглосуточно) или по телефону с 10-00 до 17-00 ежедневно. Выходной воскресенье. Продажа надувных и каркасных бассейнов осуществляется интернет-магазином оптом и в розницу, мы всегда сможем предложить лучшие цены, скидки, распродажа остатков в конце сезона.  </p>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
jQuery(document).ready(function(){
     jQuery('.nad-popup').click(function(){
          if(jQuery('.nad-div').css('display')=='none') {
               jQuery('.nad-div').css('display','block');
               jQuery('.nad-popup .arrow').attr('src','/media/tr1.jpg');
          } else {
              jQuery('.nad-div').css('display','none');
              jQuery('.nad-popup .arrow').attr('src','/media/tr2.jpg');
          }
     });
     jQuery('.kar-popup').click(function(){
          if(jQuery('.kar-div').css('display')=='none') {
               jQuery('.kar-div').css('display','block');
               jQuery('.kar-popup .arrow').attr('src','/media/tr1.jpg');
          } else {
              jQuery('.kar-div').css('display','none');
              jQuery('.kar-popup .arrow').attr('src','/media/tr2.jpg');
          }
     });     
});
</script>



<div><div><div><div>
    <script type="text/javascript">
jQuery(document).ready(function(){
jQuery('.main-content-bottom').eq(2).css('margin-top','-10px');
});
    </script>