<div class="main-description1">    
<div class="main-border-left1">
    <div class="main-border-right1">                         
    <div class="main-content1">
                                                <div class="std"><div class="page-title"><span class="customer-chosen">Мы рекомендуем</span></div>
                                                <div class="customer-description"><span>Выбор наших экспертов на основании<br/> собственного опыта и отзывов</span></div>
<div class="product-collateral" style="padding: 0px !important;">


<br/>
    <ul class="product-tabs prod-tabs-main">    
        <li id="product_tabs_description" class="tab-main active
        "><a href="javascript:void(0)">Каркасные бассейны</a></li>
        <li id="product_tabs_product.tags" class="lasting tab-main"><a href="javascript:void(0)">Надувные бассейны</a></li>
        <li id="product_tabs_reviews" class="last tab-main"><a href="javascript:void(0)">Оборудование</a></li>                                    
    </ul>

    <div class="product-tabs-content" id="product_tabs_description_contents" style="display: block;">
        <div class="main-description">
<div class="main-content-top"><div><div>&nbsp;</div></div></div>
<div class="main-border-left">
    <div class="main-border-right">                         
    <div class="main-content">
        <?php
$visibility = array(
    Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH,
    Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG
);
$category = new Mage_Catalog_Model_Category();
$category->load(5); //My cat id is 10
$_productCollection = $category->getProductCollection()->addAttributeToFilter('visibility', $visibility)->setOrder('ordered_qty', 'asc')->setPageSize(6);
$_helper = $this->helper('catalog/output');
?>
<?php if (!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <div class="category-products">   
        <?php // List mode ?>    
        <?php $_iterator = 0; ?>    
        <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

        <?php // Grid Mode ?>

        <?php $_collectionSize = $_productCollection->count() ?>
        <?php $_columnCount = $this->getColumnCount();
        $_columnCount = 2; ?>
        <?php $i = 0;
        foreach ($_productCollection as $_product): ?>
            <?php $_columnCount = 3;
            $_product = Mage::getModel('catalog/product')->load($_product->getId());
            ?>
        <?php if ($i++ % $_columnCount == 0): ?>
                <ul class="products-grid-home products-grid">
        <?php endif ?>
                <li class="item<?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?>">
                    <div class="product-images">
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize(170, 110)->setQuality(100); ?>" width="170" height="110" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                    </div>
                    <div class="product-details">
                        <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo substr($_helper->productAttribute($_product, $_product->getName(), 'name'), 0, 1000); ?></a></h2>
        <?php if ($_product->getRatingSummary()): ?>
                                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                            <?php endif; ?>

                        <div class="desc std appstockus-descstd">
                            <?php echo substr($_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description'), 0, 55); ?>
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('...') ?></a>
                        </div>
                        <div class="main-price-html">   
        <?php echo $this->getPriceHtml($_product, true) ?>
                        </div>
                        <div class="main-action-html">
                            <div class="actions">
                                <div class="appstockus-inner-actions"> 
                                    <button type="button" title="<?php echo $this->__('Details') ?>" class="button btn-details" onclick="setLocation('<?php echo $_product->getProductUrl() ?>')"><span><span><?php echo $this->__('Details') ?></span></span></button>
                                </div>
                                <div class="appstockus-fl">
                                    <?php if ($_product->isSaleable()): ?>
                                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart " onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span class="width241"><span class="width151">
                          
Добавить в корзину
                        </span></span></button>
        <?php else: ?>
                                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
        <?php endif; ?>     
                                </div>                  

                            </div></div>
                    </div>
                </li>
            <?php if ($i % $_columnCount == 0 || $i == $_collectionSize): ?>
                </ul>
        <?php endif ?>
    <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd', 'even', 'first', 'last'])</script>

    </div>
<?php endif; ?>
</div></div><div class="main-content-bottom"><div><div>&nbsp;</div></div></div></div></div>
    </div>
    <div class="product-tabs-content tags" id="product_tabs_product.tags_contents" style="display: none;">
        <div class="main-description">
<div class="main-content-top"><div><div>&nbsp;</div></div></div>
<div class="main-border-left">
    <div class="main-border-right">                         
    <div class="main-content">
        <?php
$visibility = array(
    Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH,
    Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG
);
$category = new Mage_Catalog_Model_Category();
$category->load(3); //My cat id is 10
$_productCollection = $category->getProductCollection()->addAttributeToFilter('visibility', $visibility)->setOrder('ordered_qty', 'asc')->setPageSize(6);
$_helper = $this->helper('catalog/output');
?>
<?php if (!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <div class="category-products">   
        <?php // List mode ?>    
        <?php $_iterator = 0; ?>    
        <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

        <?php // Grid Mode ?>

        <?php $_collectionSize = $_productCollection->count() ?>
        <?php $_columnCount = $this->getColumnCount();
        $_columnCount = 2; ?>
        <?php $i = 0;
        foreach ($_productCollection as $_product): ?>
            <?php $_columnCount = 3;
            $_product = Mage::getModel('catalog/product')->load($_product->getId());
            ?>
        <?php if ($i++ % $_columnCount == 0): ?>
                <ul class="products-grid-home products-grid">
        <?php endif ?>
                <li class="item<?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?>">
                    <div class="product-images">
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize(170, 110)->setQuality(100); ?>" width="170" height="110" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                    </div>
                    <div class="product-details">
                        <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo substr($_helper->productAttribute($_product, $_product->getName(), 'name'), 0, 1000); ?></a></h2>
        <?php if ($_product->getRatingSummary()): ?>
                                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                            <?php endif; ?>

                        <div class="desc std appstockus-descstd">
                            <?php echo substr($_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description'), 0, 55); ?>
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('...') ?></a>
                        </div>
                        <div class="main-price-html">   
        <?php echo $this->getPriceHtml($_product, true) ?>
                        </div>
                        <div class="main-action-html">
                            <div class="actions">
                                <div class="appstockus-inner-actions"> 
                                    <button type="button" title="<?php echo $this->__('Details') ?>" class="button btn-details" onclick="setLocation('<?php echo $_product->getProductUrl() ?>')"><span><span><?php echo $this->__('Details') ?></span></span></button>
                                </div>
                                <div class="appstockus-fl">
                                    <?php if ($_product->isSaleable()): ?>
                                       <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart " onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span class="width241"><span class="width151">
                          
Добавить в корзину
                        </span></span></button>
        <?php else: ?>
                                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
        <?php endif; ?>     
                                </div>                  

                            </div></div>
                    </div>
                </li>
            <?php if ($i % $_columnCount == 0 || $i == $_collectionSize): ?>
                </ul>
        <?php endif ?>
    <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd', 'even', 'first', 'last'])</script>

    </div>
<?php endif; ?>
</div></div><div class="main-content-bottom"><div><div>&nbsp;</div></div></div></div></div>
    </div>
    <div class="product-tabs-content " id="product_tabs_reviews_contents" style="display: none;">
        <div class="main-description">
<div class="main-content-top"><div><div>&nbsp;</div></div></div>
<div class="main-border-left">
    <div class="main-border-right">                         
    <div class="main-content">
        <?php
$visibility = array(
    Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH,
    Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG
);
$category = new Mage_Catalog_Model_Category();
$category->load(11); //My cat id is 10
$_productCollection = $category->getProductCollection()->addAttributeToFilter('visibility', $visibility)->setOrder('ordered_qty', 'asc')->setPageSize(6);
$_helper = $this->helper('catalog/output');
?>
<?php if (!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <div class="category-products">   
        <?php // List mode ?>    
        <?php $_iterator = 0; ?>    
        <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

        <?php // Grid Mode ?>

        <?php $_collectionSize = $_productCollection->count() ?>
        <?php $_columnCount = $this->getColumnCount();
        $_columnCount = 2; ?>
        <?php $i = 0;
        foreach ($_productCollection as $_product): ?>
            <?php $_columnCount = 3;
            $_product = Mage::getModel('catalog/product')->load($_product->getId());
            ?>
        <?php if ($i++ % $_columnCount == 0): ?>
                <ul class="products-grid-home products-grid">
        <?php endif ?>
                <li class="item<?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?>">
                    <div class="product-images">
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize(170, 110)->setQuality(100); ?>" width="170" height="110" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                    </div>
                    <div class="product-details">
                        <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo substr($_helper->productAttribute($_product, $_product->getName(), 'name'), 0, 1000); ?></a></h2>
        <?php if ($_product->getRatingSummary()): ?>
                                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                            <?php endif; ?>

                        <div class="desc std appstockus-descstd">
                            <?php echo substr($_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description'), 0, 55); ?>
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('...') ?></a>
                        </div>
                        <div class="main-price-html">   
        <?php echo $this->getPriceHtml($_product, true) ?>
                        </div>
                        <div class="main-action-html">
                            <div class="actions">
                                <div class="appstockus-inner-actions"> 
                                    <button type="button" title="<?php echo $this->__('Details') ?>" class="button btn-details" onclick="setLocation('<?php echo $_product->getProductUrl() ?>')"><span><span><?php echo $this->__('Details') ?></span></span></button>
                                </div>
                                <div class="appstockus-fl">
                                    <?php if ($_product->isSaleable()): ?>
                                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart " onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span class="width241"><span class="width151">
                          
Добавить в корзину
                        </span></span></button>
        <?php else: ?>
                                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
        <?php endif; ?>     
                                </div>                  

                            </div></div>
                    </div>
                </li>
            <?php if ($i % $_columnCount == 0 || $i == $_collectionSize): ?>
                </ul>
        <?php endif ?>
    <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd', 'even', 'first', 'last'])</script>

    </div>
<?php endif; ?>
</div></div><div class="main-content-bottom"><div><div>&nbsp;</div></div></div></div></div>
    </div>

  





</div>















<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magentocommerce.com for more information.
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2011 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>

<?php
$_productCollection = $this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
?>
    <?php if (!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
    <?php else: ?>
    <div class="category-products" style="display:none">   
        <?php // List mode  ?>    
        <?php $_iterator = 0; ?>    
        <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

        <?php // Grid Mode ?>

        <?php $_collectionSize = $_productCollection->count() ?>
        <?php $_columnCount = $this->getColumnCount();
        $_columnCount = 2; ?>
            <?php $i = 0;
            foreach ($_productCollection as $_product): ?>
        <?php $_columnCount = 3; ?>
        <?php if ($i++ % $_columnCount == 0): ?>
                <ul class="products-grid-home products-grid">
        <?php endif ?>
                <li class="item<?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?>">
                    <div class="product-images">
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize(170, 110)->setQuality(100); ?>" width="170" height="110" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                    </div>
                    <div class="product-details">
                        <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo substr($_helper->productAttribute($_product, $_product->getName(), 'name'), 0, 1000); ?></a></h2>
                            <?php if ($_product->getRatingSummary()): ?>
            <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
        <?php endif; ?>

                        <div class="desc std appstockus-descstd">
        <?php echo substr($_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description'), 0, 55); ?>
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('...') ?></a>
                        </div>
                        <div class="main-price-html">   
        <?php echo $this->getPriceHtml($_product, true) ?>
                        </div>
                        <div class="main-action-html">
                            <div class="actions">
                                <div class="appstockus-inner-actions"> 
                                    <button type="button" title="<?php echo $this->__('Details') ?>" class="button btn-details" onclick="setLocation('<?php echo $_product->getProductUrl() ?>')"><span><span><?php echo $this->__('Details') ?></span></span></button>
                                </div>
                                <div class="appstockus-fl">
        <?php if ($_product->isSaleable()): ?>
                                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
        <?php else: ?>
                                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                <?php endif; ?>     
                                </div>                  

                            </div></div>
                    </div>
                </li>
        <?php if ($i % $_columnCount == 0 || $i == $_collectionSize): ?>
                </ul>
        <?php endif ?>
    <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd', 'even', 'first', 'last'])</script>

    </div>
<?php endif; ?>
</div>
</div>
<div class="main-content-bottom"><div><div>&nbsp;</div></div></div>
</div>
</div>
</div>
  <script type="text/javascript">
//<![CDATA[
        Varien.Tabs = Class.create();
        Varien.Tabs.prototype = {
            initialize: function(selector) {
                var self = this;
                $$(selector + ' a').each(this.initTab.bind(this));
            },
            initTab: function(el) {
                el.href = 'javascript:void(0)';
                if ($(el.parentNode).hasClassName('active')) {
                    this.showContent(el);
                }
                el.observe('click', this.showContent.bind(this, el));
            },
            showContent: function(a) {
                var li = $(a.parentNode), ul = $(li.parentNode);
                ul.select('li', 'ol').each(function(el) {
                    console.log(el.id + '_contents');
                    var contents = $(el.id + '_contents');
                    if (el == li) {
                        el.addClassName('active');
                        contents.show();
                    } else {
                        el.removeClassName('active');
                        contents.hide();
                    }
                });
            }
        }
        new Varien.Tabs('.product-tabs');
//]]>
        jQuery(document).ready(function() {
            // jQuery('.product-tabs-content.tags .border-left').html(jQuery('.related-content').html()); 
        });
    </script>


