<?php if ($this->getTotals()): ?>
<tfoot>
	<?php $_colspan = $this->helper('tax')->displayCartBothPrices() ? 3 : 2; ?>
    <?php $ship = $this->renderTotals(null, $_colspan); ?>
    <?php $ship = str_replace('Доставка и обработка', '', $ship); ?>
    <?php $ship = str_replace('(', '', $ship); ?>
    <?php $ship = str_replace(')', '', $ship); ?>
    <?php echo $ship; ?>
    <?php echo $this->renderTotals('footer', $_colspan); ?>
    <?php if ($this->needDisplayBaseGrandtotal()):?>
    <tr>
        <td class="a-right" colspan="<?php echo $_colspan; ?>">
            <small><?php echo $this->helper('sales')->__('Your credit card will be charged for') ?></small>
        </td>
        <td class="a-right">
            <small><?php echo $this->displayBaseGrandtotal() ?></small>
        </td>
    </tr>
    <?php endif?>
</tfoot>
<?php endif; ?>
